run:
	uv run python src/invoice_parser/main.py \
		--dir inputs/ \
		--output output/bills.csv \
		--image-model hf.co/LiquidAI/LFM2-VL-3B-GGUF:F16 \
		--extractor-model hf.co/LiquidAI/LFM2-1.2B-Extract-GGUF:F16 \
		--process-existing